
###getAllDocents
GET http://localhost:3001/api/docent/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3RVc2VyIiwicGVybWlzc2lvbiI6MiwiaWF0IjoxNjU4NTA0MDk0fQ.dj__Bf5F48Fi6HnrCFOMFWnLK-yz6jlIhPopf2mVDqs

###getDocentbyID
GET http://localhost:3001/api/docent/1

###createNewDocent
POST http://localhost:3001/api/docent/new
Content-Type: application/json

{
"first_name": "asdtest2",
"last_name": "test",
"email": "tetee@hs-kl.de",
"title": "Prof. Dr",
"job_type":"Professor"
}

###updateDocent
PUT http://localhost:3001/api/docent/9/edit
Content-Type: application/json

{
"first_name": "Pedravic",
"last_name": "Barclay",
"email": "Pedra.Barclay@hs-kl",
"title": "Prof. Dr",
"job_type":"Professor"
}


###deleteDocentByID
DELETE http://localhost:3001/api/docent/120/delete

###getDocentByLastName
GET http://localhost:3001/api/docent/Doe