
###getAllDocents
GET http://localhost:3001/api/docent/

###getminimaldocentlist
GET http://localhost:3001/api/docent/list/minimal

###Overview
GET http://localhost:3001/api/docent/docent-course/overview


###getDocentbyID
GET http://localhost:3001/api/docent/1

###createNewDocent
POST http://localhost:3001/api/docent/
Content-Type: application/json

{
"first_name": "asdtest2",
"last_name": "test",
"title": "Prof. Dr",
"job_ty
}

###updateDocent
PUT http://localhost:3001/api/docent/1/
Content-Type: application/json

{
"first_name": "Max",
"last_name": "Mustermann",
"email": "max@mustermann.de"
}


###deleteDocentByID
DELETE http://localhost:3001/api/docent/243/

###getDocentByLastName
POST http://localhost:3001/api/docent/by-last-name
Content-Type: application/json

{
"last_name": "LfbA NN WInfo
"
}
