
###getAlldocentCourse
GET http://localhost:3001/api/docent-course/




###
POST http://localhost:3001/api/docent-course/
Content-Type: application/json

{
"docent_id": 1,
"course_id": 446,
"registered": 1
}

###get docent course by course_id docent_id
POST http://localhost:3001/api/docent-course/by-ids
Content-Type: application/json

{
"docent_id": 195,
"course_id": 447
}

###get docent course by course_id docent_id
POST http://localhost:3001/api/docent-course/by-course-id
Content-Type: application/json

{
"course_id": 577
}

###updatedocentCourse
PATCH http://localhost:3001/api/docent-course/217/
Content-Type: application/json

{
"registered": 0
}


###deletedocentCourseByID
DELETE http://localhost:3001/api/docent-course/235/