
###getAllErGroup
GET http://localhost:3001/api/er-group/


###get er Groupid by name and er_id
POST http://localhost:3001/api/er-group/by-name
Content-Type: application/json

{
"name": "main",
"exam_regulations_id": 6
}

###
POST http://localhost:3001/api/er-group/
Content-Type: application/json

{
"name": "sd",
"exam_regulations_id": 6
}

###updateerGroup
PATCH http://localhost:3001/api/er-group/3/
Content-Type: application/json

{
"exam_regulations_id": 2
}


###deleteerGroupByID
DELETE http://localhost:3001/api/er-group/306/

###get senester
GET http://localhost:3001/api/er-group/6/number-of-semesters

###get courses
GET http://localhost:3001/api/er-group/6/courses