
###getAllPO
GET http://localhost:3001/api/exam-regulations/


###create PO
POST http://localhost:3001/api//exam-regulations/
Content-Type: application/json

{
"year":2020,
"exam_regulations_group":"",
"major_id":1
}

###delet PO 
DELETE http://localhost:3001/api/exam-regulations/27/


###get senester
GET http://localhost:3001/api/exam-regulations/6/number-of-semesters



###get courses
GET http://localhost:3001/api/exam-regulations/6/courses

###get er-groups
GET http://localhost:3001/api/exam-regulations/6/er-groups

###get existing module
GET http://localhost:3001/api/exam-regulations/17/module/1087



###get courses
GET http://localhost:3001/api/exam-regulations/all/overview/courses
