POST https://localhost:3001/api/auth/create-session
Content-Type: application/json

{
"username": "testAdmin",
"password": "BA_2022"
}

###
POST http://localhost:3001/api/auth/delete-session
Content-Type: application/json

{
"logout": "true"
}

###
GET http://localhost:3001/api/auth/existing-docent
Content-Type: application/json

{
"lastName": "mustermann",
"firstName": "max"
}
