
###getAllmajors
GET http://localhost:3001/api/major/

###getmajorbyID
GET http://localhost:3001/api/major/1

###getexamreg
GET http://localhost:3001/api/major/1/exam-regulations/



###createNewmajor
POST http://localhost:3001/api/major/
Content-Type: application/json

{
"name":"International Business Administration",
"degree":"Bachelor"
}

###getMajorbynamedegree
POST http://localhost:3001/api/major/by-name-degree
Content-Type: application/json

{
"name":"Mittelstandsökonomie",
"degree":"Bachelor"
}



###updatemajor
PATCH  http://localhost:3001/api/major/6/
Content-Type: application/json

{

}


###deletemajorByID
DELETE http://localhost:3001/api/major/13/



###create PO
POST http://localhost:3001/api//examRegulations/
Content-Type: application/json

{
"year":20,
"exam_regulations_group":"",
"major_id":12
}
