
###getAllModule
GET http://localhost:3001/api/module/

###getmodule
GET http://localhost:3001/api/module/449/



###getcourses 
GET http://localhost:3001/api/module/449/courses



###createModule
POST http://localhost:3001/api//module/
Content-Type: application/json

{
"name":"test",
"semester":1.6234,
"sws":3,
"visibility":1
}

###deletModule
DELETE http://localhost:3001/api/module/1/

###getModuleByNAme
POST http://localhost:3001/api/module/by-name
Content-Type: application/json

{
"name":"testtesttesttest"
}
