
###getAllModule
GET http://localhost:3001/api/module/

###getmodule
GET http://localhost:3001/api/module/sd/



###getcourses 
GET http://localhost:3001/api/module/478/courses



###createModule
POST http://localhost:3001/api//module/
Content-Type: application/json

{
"name":"test",
"semester":1.6234,
"sws":3000000000,
"visibility":1
}

###deletModule
DELETE http://localhost:3001/api/module/1/

###getModuleByNAme
POST http://localhost:3001/api/module/by-name-semester
Content-Type: application/json

{
"name":"Englisch Grundlagen",
"semester":1
}
