
###getAllmoduleErGroup
GET http://localhost:3001/api/moduleErGroup/



### create modulergroup
POST http://localhost:3001/api/moduleErGroup/
Content-Type: application/json

{
    "er_group_id": 300,
    "module_id": 365
}

### check
POST http://localhost:3001/api/moduleErGroup/exists
Content-Type: application/json

{
    "er_group_id": 300,
    "module_id": 3
}



###updatemoduleErGroup
PATCH http://localhost:3001/api/moduleErGroup/3/
Content-Type: application/json

{
"exam_regulations_id": 2
}

###deletemoduleErGroupByID
DELETE http://localhost:3001/api/moduleErGroup/3/