
###getAllusers
GET http://localhost:3001/api/user/


###getuserbyID
GET http://localhost:3001/api/user/1

###get total sws
GET http://localhost:3001/api/user/my-account/total-lsws


###get visible courses
GET http://localhost:3001/api/user/my-account/visible-courses


###getuserbyUsername
GET http://localhost:3001/api/user/username/testUser


###getDocent
GET http://localhost:3001/api/user/1/docent



###createNewuser
POST http://localhost:3001/api/user/
Content-Type: application/json

{
"username": "faddfgasg",
"password": "BA_2022",
"permission_id": 1,
"docent_id": 1
}

###updateuser
PATCH  http://localhost:3001/api/user/1/


{
"docent_id": 1
}


###FIXME: weird error 
PATCH  http://localhost:3001/api/user/1/


{
"docent": 1
}


###deleteuserByID
DELETE http://localhost:3001/api/user/113/

