
###getAllDocents
GET http://localhost:3001/api/docent/

###getDocentbyID
GET http://localhost:3001/api/docent/1

###createNewDocent
POST http://localhost:3001/api/docent/new
Content-Type: application/json

{
"first_name": "asdtest2",
"last_name": "test",
"email": "tetee@hs-kl.de",
"title": "Prof. Dr",
"job_type":"Professor"
}

###updateDocent
PUT http://localhost:3001/api/docent/9/edit
Content-Type: application/json

{
"first_name": "Pedravic",
"last_name": "Barclay",
"email": "Pedra.Barclay@hs-kl",
"title": "Prof. Dr",
"job_type":"Professor"
}


###deleteDocentByID
DELETE http://localhost:3001/api/docent/120/delete

###getDocentByLastName
GET http://localhost:3001/api/docent/Doe