module.exports = {
    COMMENT: "comment",
    COURSE: "course",
    DOCENT: "docent",
    DOCENT_COURSE: "docent_course",
    EXAM_REGULATIONSs: "exam_regulations",
    MAJOR: "major",
    ER_GROUP: "er_group",
    MODUL: "module",
    MODULE_ER_GROUP: "module_er_group",
    NOTICE: "notice",
    PERMISSION: "permission",
    USER: "user",
    COMPULSORY_MODULE: "compulsory_module",
}