module.exports = {
    comment: "comment",
    course: "course",
    docent: "docent",
    docentCourse: "docent_course",
    examRegulations: "exam_regulations",
    major: "major",
    erGroup: "er_group",
    module: "module",
    moduleMajorGroup: "module_major_group",
    notice: "notice",
    permission: "permission",
    user: "user",
    compulsoryModule: "compulsory_module",
}